#!/bin/bash
MYPATH=.
REGIONILATESTFILE="$MYPATH/COVID-19/dati-regioni/dpc-covid19-ita-regioni-latest.csv"

	tail -21 "$REGIONILATESTFILE" | while read RIGA; do
	NOTA=$(echo "$RIGA" | cut -f21- -d"," | sed '/^[[:space:]]*$/d' | sed "s/\"//g" | sed -E 's/[[:space:]]([:,.?!])/\1/g')

		if [ "$NOTA" != "" ];then
			REGIONENOTA=$(echo "$RIGA" | cut -f4 -d",")
			echo "<b>$REGIONENOTA</b> - $NOTA<br>" 
		fi
	done

